// components/ui/Form.tsx
import React from "react";

export function Field({children}:{children:React.ReactNode}){return(<div className="space-y-2">{children}</div>);}
export function Label({htmlFor,children,required=false}:{htmlFor?:string;children:React.ReactNode;required?:boolean;}){return(<label htmlFor={htmlFor} className="block text-sm font-medium text-gray-200">{children}{required&&<span className="ml-1 text-rose-400">*</span>}</label>);}
export function Helper({children}:{children:React.ReactNode}){return(<p className="text-xs text-gray-400">{children}</p>);}
export function Input(props:React.InputHTMLAttributes<HTMLInputElement>){return(<input {...props} className={["w-full rounded-md border border-white/10 bg-slate-900/70 px-3 py-2 text-sm text-white placeholder-gray-500 outline-none ring-0 focus:border-amber-400 focus:outline-none",props.className].filter(Boolean).join(" ")} />);}
export function Textarea(props:React.TextareaHTMLAttributes<HTMLTextAreaElement>){return(<textarea {...props} className={["w-full rounded-md border border-white/10 bg-slate-900/70 px-3 py-2 text-sm text-white placeholder-gray-500 outline-none ring-0 focus:border-amber-400 focus:outline-none",props.className].filter(Boolean).join(" ")} />);}
export function Select(props:React.SelectHTMLAttributes<HTMLSelectElement>){return(<select {...props} className={["w-full rounded-md border border-white/10 bg-slate-900/70 px-3 py-2 text-sm text-white outline-none focus:border-amber-400",props.className].filter(Boolean).join(" ")} />);}
export function RadioGroup({name,options,defaultValue,required=false}:{name:string;options:{value:string;label:string;hint?:string}[];defaultValue?:string;required?:boolean;}){return(<div className="space-y-2">{options.map((o,i)=>{const id=`${name}-${i}`;return(<label key={o.value} htmlFor={id} className="flex cursor-pointer items-start gap-3 rounded-md border border-white/10 bg-slate-900/50 p-3 hover:border-amber-400/60"><input id={id} name={name} type="radio" value={o.value} defaultChecked={defaultValue===o.value} required={required} className="mt-1 h-4 w-4 cursor-pointer accent-amber-400" /><div><div className="text-sm text-white">{o.label}</div>{o.hint&&<div className="text-xs text-gray-400">{o.hint}</div>}</div></label>);})}</div>);}
export function Checkbox({id,label,defaultChecked}:{id:string;label:string;defaultChecked?:boolean;}){return(<label htmlFor={id} className="flex items-center gap-3 text-sm text-white"><input id={id} type="checkbox" defaultChecked={defaultChecked} className="h-4 w-4 accent-amber-400" /><span>{label}</span></label>);}
export function Section({title,children}:{title:string;children:React.ReactNode;}){return(<section className="space-y-4 rounded-xl border border-white/10 bg-slate-950/70 p-4 sm:p-6"><h3 className="text-sm font-semibold tracking-wide text-gray-200">{title}</h3>{children}</section>);}
export function Submit({children}:{children:React.ReactNode}){return(<button type="submit" className="inline-flex items-center justify-center rounded-md bg-amber-500 px-4 py-2 text-sm font-semibold text-black shadow hover:bg-amber-400 focus:outline-none">{children}</button>);}
